name: teachme
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.1
  simple_animations: ^5.0.0+3
  cached_network_image: ^3.1.0
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  flutter_svg: ^2.0.1
  #service locator
  get_it: ^6.0.0
  #bloc for state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  #value equality
  equatable: ^2.0.5
  #functional programing thingies
  dartz: ^0.10.1
  #remote API
#  connectivity: ^0.4.3+7
  http: ^0.13.0
  #local cache
  shared_preferences: ^2.0.17
  persistent_bottom_nav_bar: any
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.3.5
  form_field_validator: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/category/
